//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookpouch.Lang {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookpouch.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filter.
        /// </summary>
        internal static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with copying {0} into the library..
        /// </summary>
        internal static string BookCopyError {
            get {
                return ResourceManager.GetString("BookCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to permanently delete {0}?.
        /// </summary>
        internal static string BookDeleteConfirm {
            get {
                return ResourceManager.GetString("BookDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete book?.
        /// </summary>
        internal static string BookDeleteConfirmTitle {
            get {
                return ResourceManager.GetString("BookDeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BookGridClearFilter {
            get {
                return ResourceManager.GetString("BookGridClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BookGridEdit {
            get {
                return ResourceManager.GetString("BookGridEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir.
        /// </summary>
        internal static string BookGridOpenDir {
            get {
                return ResourceManager.GetString("BookGridOpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was not able to retrieve infomartion about the book from the storage. Maybe the book file wasn&apos;t found, or the database record is corrupted..
        /// </summary>
        internal static string BookInfoNotAvailable {
            get {
                return ResourceManager.GetString("BookInfoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wasn&apos;t able to save the supplied value about the book..
        /// </summary>
        internal static string BookInfoSaveError {
            get {
                return ResourceManager.GetString("BookInfoSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning the library database....
        /// </summary>
        internal static string BusyCleaningDb {
            get {
                return ResourceManager.GetString("BusyCleaningDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to permanently delete {0} book/s?.
        /// </summary>
        internal static string DeleteBooksConfirm {
            get {
                return ResourceManager.GetString("DeleteBooksConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not have write access to this folder..
        /// </summary>
        internal static string DirAccessDenied {
            get {
                return ResourceManager.GetString("DirAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wasn&apos;t able to find the specified directory ({0}) for storing books..
        /// </summary>
        internal static string DirNotFound {
            get {
                return ResourceManager.GetString("DirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard book?.
        /// </summary>
        internal static string DiscardBook {
            get {
                return ResourceManager.GetString("DiscardBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete preset.
        /// </summary>
        internal static string DiscardFilterPreset {
            get {
                return ResourceManager.GetString("DiscardFilterPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the {0} filter preset?.
        /// </summary>
        internal static string DiscardFilterPresetConfirm {
            get {
                return ResourceManager.GetString("DiscardFilterPresetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was not able to remove this book: {0}.
        /// </summary>
        internal static string DiscardingBookFailed {
            get {
                return ResourceManager.GetString("DiscardingBookFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Author:.
        /// </summary>
        internal static string EditBookAuthor {
            get {
                return ResourceManager.GetString("EditBookAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes in the window for book details editing are automatically saved and therefore you don&apos;t need to click any &quot;Save&quot; button..
        /// </summary>
        internal static string EditBookAutoSavePopup {
            get {
                return ResourceManager.GetString("EditBookAutoSavePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Category:.
        /// </summary>
        internal static string EditBookCategory {
            get {
                return ResourceManager.GetString("EditBookCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Created:.
        /// </summary>
        internal static string EditBookCreated {
            get {
                return ResourceManager.GetString("EditBookCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Description: .
        /// </summary>
        internal static string EditBookDescription {
            get {
                return ResourceManager.GetString("EditBookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete book.
        /// </summary>
        internal static string EditBookDiscard {
            get {
                return ResourceManager.GetString("EditBookDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Favorite:.
        /// </summary>
        internal static string EditBookFavorite {
            get {
                return ResourceManager.GetString("EditBookFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language:.
        /// </summary>
        internal static string EditBookLanguage {
            get {
                return ResourceManager.GetString("EditBookLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Path:.
        /// </summary>
        internal static string EditBookPath {
            get {
                return ResourceManager.GetString("EditBookPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Published:.
        /// </summary>
        internal static string EditBookPublished {
            get {
                return ResourceManager.GetString("EditBookPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_eries:.
        /// </summary>
        internal static string EditBookSeries {
            get {
                return ResourceManager.GetString("EditBookSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sync:.
        /// </summary>
        internal static string EditBookSync {
            get {
                return ResourceManager.GetString("EditBookSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Title:.
        /// </summary>
        internal static string EditBookTitle {
            get {
                return ResourceManager.GetString("EditBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wasn&apos;t ale to get any information from the Epub file, it may be corrupted or is missing some key files..
        /// </summary>
        internal static string EpubCorrupted {
            get {
                return ResourceManager.GetString("EpubCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing the EXTH header, even though it claims that it has one and therefore I wasn&apos;t able to extract any information from it..
        /// </summary>
        internal static string ExthHeaderMissing {
            get {
                return ResourceManager.GetString("ExthHeaderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I encountered some problems with fetching the EXTH header in {0}: {1}.
        /// </summary>
        internal static string ExthProblemFetching {
            get {
                return ResourceManager.GetString("ExthProblemFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string FieldAuthor {
            get {
                return ResourceManager.GetString("FieldAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string FieldCategory {
            get {
                return ResourceManager.GetString("FieldCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string FieldCreated {
            get {
                return ResourceManager.GetString("FieldCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FieldDescription {
            get {
                return ResourceManager.GetString("FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ★.
        /// </summary>
        internal static string FieldFavorite {
            get {
                return ResourceManager.GetString("FieldFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string FieldLanguage {
            get {
                return ResourceManager.GetString("FieldLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string FieldPath {
            get {
                return ResourceManager.GetString("FieldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string FieldPublished {
            get {
                return ResourceManager.GetString("FieldPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string FieldPublisher {
            get {
                return ResourceManager.GetString("FieldPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string FieldSeries {
            get {
                return ResourceManager.GetString("FieldSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ⇪.
        /// </summary>
        internal static string FieldSync {
            get {
                return ResourceManager.GetString("FieldSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string FieldTitle {
            get {
                return ResourceManager.GetString("FieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All parameters entered in this filter are applied automatically to the book list. If the book list has already some other filter parameters active on it, the new parameters entered in this window will be merged with the existing ones. .
        /// </summary>
        internal static string FilterFirstUsePopup {
            get {
                return ResourceManager.GetString("FilterFirstUsePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the filter preset failed, because another preset with the chosen name already exists..
        /// </summary>
        internal static string FilterSavingPresetDuplicate {
            get {
                return ResourceManager.GetString("FilterSavingPresetDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter preset was successfully saved..
        /// </summary>
        internal static string FilterSavingPresetSuccessful {
            get {
                return ResourceManager.GetString("FilterSavingPresetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start Bookpouch during the computer boot and minimize it into tray.
        /// </summary>
        internal static string HintAutoStart {
            get {
                return ResourceManager.GetString("HintAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to mark this book as one of your favorites..
        /// </summary>
        internal static string HintBookGridFavorite {
            get {
                return ResourceManager.GetString("HintBookGridFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to decide if you want to sync this book to your reader or not..
        /// </summary>
        internal static string HintBookGridSync {
            get {
                return ResourceManager.GetString("HintBookGridSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When covers are extracted from the book files, only extract covers where height is larger than width. (This can filter out some incorrect images being used as covers).
        /// </summary>
        internal static string HintCheckCoverDimensions {
            get {
                return ResourceManager.GetString("HintCheckCoverDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the active filter..
        /// </summary>
        internal static string HintClearFilter {
            get {
                return ResourceManager.GetString("HintClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered date is: equal to (=), larger than (&gt;), or smaller than (&lt;) the selected date..
        /// </summary>
        internal static string HintDateRange {
            get {
                return ResourceManager.GetString("HintDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you are done typing the category&apos;s name, type ; (semicolon) or , (comma) to add it to the list..
        /// </summary>
        internal static string HintEditBookCategory {
            get {
                return ResourceManager.GetString("HintEditBookCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover image for this book. You can select another image by clicking on this picture, or remove the existing image by right clicking on it..
        /// </summary>
        internal static string HintEditBookCoverImage {
            get {
                return ResourceManager.GetString("HintEditBookCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark this book as one of your favorites.
        /// </summary>
        internal static string HintEditBookFavorite {
            get {
                return ResourceManager.GetString("HintEditBookFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this book from the library.
        /// </summary>
        internal static string HintEditBookRemove {
            get {
                return ResourceManager.GetString("HintEditBookRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book will by copied into your reader during synchronization.
        /// </summary>
        internal static string HintEditBookSync {
            get {
                return ResourceManager.GetString("HintEditBookSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the preset to be saved. After you type the name, hit Enter to save the preset or Escape to cancel the saving..
        /// </summary>
        internal static string HintFilterPresetName {
            get {
                return ResourceManager.GetString("HintFilterPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string HintMenuAbout {
            get {
                return ResourceManager.GetString("HintMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new books into the library.
        /// </summary>
        internal static string HintMenuAdd {
            get {
                return ResourceManager.GetString("HintMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter the list of books and display only entries matching the given parameters.
        /// </summary>
        internal static string HintMenuFilter {
            get {
                return ResourceManager.GetString("HintMenuFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-generate the book file tree. (Use this, if you manually manipulated with folders included in the library).
        /// </summary>
        internal static string HintMenuRegenerateTree {
            get {
                return ResourceManager.GetString("HintMenuRegenerateTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open library&apos;s root directory.
        /// </summary>
        internal static string HintMenuRootDir {
            get {
                return ResourceManager.GetString("HintMenuRootDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string HintMenuSettings {
            get {
                return ResourceManager.GetString("HintMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize files on the connected ebook reader with local Bookpouch library.
        /// </summary>
        internal static string HintMenuSync {
            get {
                return ResourceManager.GetString("HintMenuSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While displaying a list of categories, or using the categories for search, only use categories manually added to books. (Categories are also extracted and added automatically from some books, but they can often be vague, or too broad and can litter the category list.).
        /// </summary>
        internal static string HintOnlyManualCategories {
            get {
                return ResourceManager.GetString("HintOnlyManualCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only allow one instance of Bookpouch to run at the same time.
        /// </summary>
        internal static string HintOnlyOne {
            get {
                return ResourceManager.GetString("HintOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the active filter parameters as a preset, which you can later use..
        /// </summary>
        internal static string HintSavePreset {
            get {
                return ResourceManager.GetString("HintSavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start sync, when compatible reader is connected to the computer.
        /// </summary>
        internal static string HintSettingsAutosync {
            get {
                return ResourceManager.GetString("HintSettingsAutosync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory in which Bookpouch searches for book files to work with..
        /// </summary>
        internal static string HintSettingsBooksDir {
            get {
                return ResourceManager.GetString("HintSettingsBooksDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug console displays runtime information about this application, this information will be probably of no use to you as an user..
        /// </summary>
        internal static string HintSettingsDebug {
            get {
                return ResourceManager.GetString("HintSettingsDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of the description displayed for books in the book list..
        /// </summary>
        internal static string HintSettingsDescriptionMaxLength {
            get {
                return ResourceManager.GetString("HintSettingsDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory on the device, where all the books are stored. This is the directory which Bookpouch will use, while working with the device..
        /// </summary>
        internal static string HintSettingsDir {
            get {
                return ResourceManager.GetString("HintSettingsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name of the reader device, usually identical to the marketing name of the reader. (For example: kindle&apos;s model name is kindle).
        /// </summary>
        internal static string HintSettingsModel {
            get {
                return ResourceManager.GetString("HintSettingsModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device&apos;s Plug and play ID. Usually identical to the model name. But it can differ..
        /// </summary>
        internal static string HintSettingsPnp {
            get {
                return ResourceManager.GetString("HintSettingsPnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the reader with which you are going to be using the Bookpouch.
        /// </summary>
        internal static string HintSettingsReader {
            get {
                return ResourceManager.GetString("HintSettingsReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show splashscreen while the application loads.
        /// </summary>
        internal static string HintSettingsSplashscreen {
            get {
                return ResourceManager.GetString("HintSettingsSplashscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing this application causes it to minimize itself into the system tray instead. (AutoSync will be still working this way).
        /// </summary>
        internal static string HintSettingsTray {
            get {
                return ResourceManager.GetString("HintSettingsTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The info queue was deleted..
        /// </summary>
        internal static string InfoQueueDeleted {
            get {
                return ResourceManager.GetString("InfoQueueDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing the MOBI header and therefore I am not able to extract any information from it..
        /// </summary>
        internal static string MobiHeaderMissing {
            get {
                return ResourceManager.GetString("MobiHeaderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavePreset {
            get {
                return ResourceManager.GetString("SavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the directory in which you keep your eBooks stored, or press cancel to stay with the current directory: {0}.
        /// </summary>
        internal static string SelectBookDirPrompt {
            get {
                return ResourceManager.GetString("SelectBookDirPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aut_o start:.
        /// </summary>
        internal static string SettingsAutoStart {
            get {
                return ResourceManager.GetString("SettingsAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AutoSync:.
        /// </summary>
        internal static string SettingsAutosync {
            get {
                return ResourceManager.GetString("SettingsAutosync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Book directory:.
        /// </summary>
        internal static string SettingsBookDir {
            get {
                return ResourceManager.GetString("SettingsBookDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book _directory:.
        /// </summary>
        internal static string SettingsBooksDir {
            get {
                return ResourceManager.GetString("SettingsBooksDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check _covers:.
        /// </summary>
        internal static string SettingsCheckCoverDimensions {
            get {
                return ResourceManager.GetString("SettingsCheckCoverDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show console.
        /// </summary>
        internal static string SettingsConsole {
            get {
                return ResourceManager.GetString("SettingsConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Debug:.
        /// </summary>
        internal static string SettingsDebug {
            get {
                return ResourceManager.GetString("SettingsDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max desc. _len.:.
        /// </summary>
        internal static string SettingsDescriptionMaxLength {
            get {
                return ResourceManager.GetString("SettingsDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language:.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Model:.
        /// </summary>
        internal static string SettingsModel {
            get {
                return ResourceManager.GetString("SettingsModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual _categ.:.
        /// </summary>
        internal static string SettingsOnlyManualCategories {
            get {
                return ResourceManager.GetString("SettingsOnlyManualCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One _instance:.
        /// </summary>
        internal static string SettingsOnlyOne {
            get {
                return ResourceManager.GetString("SettingsOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PnP ID:.
        /// </summary>
        internal static string SettingsPnp {
            get {
                return ResourceManager.GetString("SettingsPnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reader:.
        /// </summary>
        internal static string SettingsReader {
            get {
                return ResourceManager.GetString("SettingsReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is this?.
        /// </summary>
        internal static string SettingsReaderCustomHint {
            get {
                return ResourceManager.GetString("SettingsReaderCustomHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Splashscreen:.
        /// </summary>
        internal static string SettingsSplashScreen {
            get {
                return ResourceManager.GetString("SettingsSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close into _tray:.
        /// </summary>
        internal static string SettingsTray {
            get {
                return ResourceManager.GetString("SettingsTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new books....
        /// </summary>
        internal static string SyncAddingBooks {
            get {
                return ResourceManager.GetString("SyncAddingBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for connected {0}....
        /// </summary>
        internal static string SyncDeviceSearch {
            get {
                return ResourceManager.GetString("SyncDeviceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was unable to sync {0}..
        /// </summary>
        internal static string SyncFileCopyFailed {
            get {
                return ResourceManager.GetString("SyncFileCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected supported files are being added into the library....
        /// </summary>
        internal static string SyncFilesAdded {
            get {
                return ResourceManager.GetString("SyncFilesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization was successfully finished..
        /// </summary>
        internal static string SyncFinished {
            get {
                return ResourceManager.GetString("SyncFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-scanning and cleaning up the library data structure....
        /// </summary>
        internal static string SyncingDataStructure {
            get {
                return ResourceManager.GetString("SyncingDataStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wasn&apos;t able to find any connected readers..
        /// </summary>
        internal static string SyncNoReadersFound {
            get {
                return ResourceManager.GetString("SyncNoReadersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified directory \&quot;{0}\&quot; wasn&apos;t found on the connected reader: {1}..
        /// </summary>
        internal static string SyncReaderDirNotFound {
            get {
                return ResourceManager.GetString("SyncReaderDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected an unknown reader device and therefore you will need to manually input the identification strings, so that your reader can be correctly recognized and handled by Bookpouch.\nHover over the fields with your cursor to display tooltips..
        /// </summary>
        internal static string UnknownDeviceHint {
            get {
                return ResourceManager.GetString("UnknownDeviceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
